version: '3.7'

volumes:
  node_modules_server:
  node_modules_front:

services:
  app_wine_server:
    build:
      context: ./app_wine_server
    volumes:
      - node_modules_server:/app/node_modules
      - ./app_wine_server:/app
    command: node_modules/nodemon/bin/nodemon.js -w /app /app/src/index.js
    ports:
      - 3000:3000

  app_wine_server_lint:
    build:
      context: ./app_wine_server
    volumes:
      - node_modules_server:/app/node_modules
      - ./app_wine_server:/app
    command: ./node_modules/.bin/eslint .

  app_wine_server_tests:
    build:
      context: ./app_wine_server
    volumes:
      - node_modules_server:/app/node_modules
      - ./app_wine_server:/app
    command: ./node_modules/.bin/ava

  app_wine_front_lint:
    build:
      context: ./app_wine_front
    volumes:
      - node_modules_front:/app/node_modules
      - ./app_wine_front:/app
    command: ./node_modules/.bin/eslint .

  app_wine_front:
    build:
      context: ./app_wine_front
    volumes:
      - node_modules_front:/app/node_modules
      - ./app_wine_front:/app
    command: ./node_modules/.bin/webpack-dev-server --mode development --open --config config/webpack.config.js --host 0.0.0.0 --watch-aggregate-timeout 500 --watch-poll 1000
    ports:
      - 8080:8080

  app_wine_front_tests:
    build:
      context: ./app_wine_front
    volumes:
      - node_modules_front:/app/node_modules
      - ./app_wine_front:/app
    command: ./node_modules/.bin/ava
