version: '3.7'

volumes:
  node_modules_server:

services:
  app_wine_server:
    build:
      context: ./app_wine_server
    volumes:
      - node_modules_server:/app/node_modules
      - ./app_wine_server:/app
    command: node_modules/nodemon/bin/nodemon.js -w /app /app/src/index.js
    ports:
      - 3000:3000

  app_wine_server_lint:
    build:
      context: ./app_wine_server
    volumes:
      - node_modules_server:/app/node_modules
      - ./app_wine_server:/app
    command: ./node_modules/.bin/eslint .

  app_wine_server_tests:
    build:
      context: ./app_wine_server
    volumes:
      - node_modules_server:/app/node_modules
      - ./app_wine_server:/app
    command: ./node_modules/.bin/ava
